### ISSUE TITLE
Silent install without public desktop icon?

### ISSUE THREAD

**Issue by Grabou** [torakiki/pdfsam#591] opened 2024-06-21 11:07 UTC
Hello,

I want to silently install PDFsam Basic without creating an icon on the users' desktop (this file: C:\Users\Public\Desktop\PDFsam Basic.lnk).

I was checking [this page](https://github.com/torakiki/pdfsam/wiki/Properties-and-arguments) and realized that there doesn't seem to be a way to refuse the creation of the shortcut.

Is there a hidden setting or do I have to create a TRANSFORMS=myfile.mst file by fiddling with the parameters of the original MSI with Orca?

Thanks for your help and for this wonderful tool!

**Comment by torakiki** [comment] 2024-07-29 07:34
I think this is a duplicate of https://github.com/torakiki/pdfsam/issues/388

**Closed by torakiki** 2024-07-29 07:34 UTC
