### ISSUE TITLE
Weird icons on GUI

### ISSUE THREAD

**Issue by medmedin2014** [torakiki/pdfsam#166] opened 2016-05-20 17:09 UTC
I tried to install PDFSam Basic 3.0.3, but when i launched the app i saw really weird and abnormal icons on GUI (See attached images)
I use Ubuntu Mate 16.04 32bits with OpenJDK 1.8.0_91 and installed the debian installer provided on the official website. (updated tested with zip installer and get same result)
![pdf split and merge basic edition_003](https://cloud.githubusercontent.com/assets/7027319/15435701/bb7f4cbc-1eb5-11e6-91c3-2a38972adadf.png)
![pdf split and merge basic edition_002](https://cloud.githubusercontent.com/assets/7027319/15435702/bbff377e-1eb5-11e6-9041-d447bcfa67cd.png)

**Comment by KinnaT** [comment] 2016-05-24 18:04
It looks like it's unable to bring in the fontawesome icon font. The boxes are what your computer is inserting in lieu of whatever characters in whatever required font it can't find. It should look like this:
![5-24-16 12-51-47](https://cloud.githubusercontent.com/assets/4543324/15514358/61f9fc9a-21ae-11e6-8991-b4171f5bd334.png)
In the dependencies is: de.jensd:fontawesomefx:jar:8.6:compile
Java and Ubuntu aren't my strong suits or I'd delve into the source code myself.

**Comment by torakiki** [comment] 2016-06-09 17:28
I can confirm the issue but I don't get any error message or pointer to figure what is the problem.. also, it seems to be related to the Mate version of Ubuntu because it works fine on a couple of standard Ubuntu boxes I have...

**Comment by torakiki** [comment] 2016-08-23 08:56
I switched to Ubuntu Mate 16.04 myself.. 64bits and when using OpenJDK 1.8.0_91 all the icons are fine so I guess it has something with the 32bits version..

**Comment by torakiki** [comment] 2017-01-20 14:08
Could you please verify if this is still an issue with the latest PDFsam and OpenJDK ?

**Comment by medmedin2014** [comment] 2017-01-21 19:07
I repeated the test with OpenJDK v1.8.0_111 and OpenJDK v9-ea+152 on Ubuntu Mate 16.04.1 32bits using the latest release PDFSam v3.2.5 as debian and also as compressed file (zip), and i always get the same old behavior as before. I think the problem resides in FontAwsomeFX library because I downloaded an app called [Glyph Browser](http://jensd.de/apps/fontawesomefx-glyphsbrowser/fontawesomefx-glyphsbrowser-all-1.0.jar) that use also FontAwsomeFX library and it can't display almost of the Material Design Icons correctly 
![screenshot at 2017-01-21 19-04-43](https://cloud.githubusercontent.com/assets/7027319/22176938/b1b20756-e00c-11e6-9ab4-7bd589c99ca4.png)

**Comment by torakiki** [comment] 2017-01-23 18:27
Indeed it seems you nailed the issue. I reported the issue https://bitbucket.org/Jerady/fontawesomefx/issues/40/fontawesomefx-icons-displayed-as-garbage

**Comment by torakiki** [comment] 2017-01-30 18:10
After some investigation it ended up here http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8173468
Let's see what they say

**Comment by torakiki** [comment] 2017-05-02 07:32
This was closed in Java 8u121

**Closed by torakiki** 2017-05-02 07:32 UTC
