### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by MortenHannemose** [torakiki/pdfsam#419] opened 2020-07-30 12:32 UTC
I just did a clean install, and after launch the CPU-usage is around 3-9% when the program is just left open and not used.

This seems unusually high for a program not doing anything. My processor is an Intel i7-6600U, so not completely ancient.

**Comment by torakiki** [comment] 2020-07-30 17:25
What OS and PDFsam version?

**Comment by MortenHannemose** [comment] 2020-07-30 17:33
Windows 10.
It happens for me both with PDFsam 4.1.4 and 3.3.6

**Comment by Photon89** [comment] 2021-12-19 13:22
I have the same issue on Manjaro Linux with an i5-1135G7. I suspect the green animated "what is new" button to be the cause of the high CPU load in idle. After clicking the button, such that the news are marked as read, the CPU load is at 0% again. I now deactivated the new search in the settings as a workaround, but of course it would be nice if the button animation didn't use up so much CPU power.

**Comment by torakiki** [comment] 2023-01-25 13:59
That animation has been removed in version 5, there is only a notification icon now.

**Closed by torakiki** 2023-01-25 13:59 UTC
